services:
  redis:
    image: redis
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 60 1 --loglevel warning
    volumes: 
      - redis:/data
volumes:
  redis:
    driver: local
