services:
  ollama:
    image: ollama/ollama
    ports:
      - 11434:11434
    volumes:
      - /root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
              driver: amd
              count: 1
