services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: "db"
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - "3306:3306"
    expose:
      # Opens port 3306 on the container
      - "3306"
#     volumes:
#       - mysql-db:/var/lib/mysql
# # Names our volume
# volumes:
#   mysql-db:
